### ISSUE TITLE
Werbegeschenke: Flugbeutel

### ISSUE THREAD

**Issue by aobermeier** [aobermeier/Work#1]
**Anforderung:** Plastikbeutel mit Zipp-Verschluss (ca. 500 – 1000 Stück)

Auf Flugreisen gibt es für Flüssigkeiten genormte durchsichtige Beutel mit Zippverschluss (wie bei Toppits). Für unsere Werbegeschenke wollen wir gern solche Beutel aus etwas besserem Kunststoff.

Gewünschter Druck: 2-farbiges Logo, einseitig

Anfrage an 2 Agenturen am 19.12 - nur 1 hat geantwortet

[Angebot 20013541.pdf](https://github.com/aobermeier/Work/files/719619/Angebot.20013541.pdf)

**Comment by aobermeier** [comment]
**Anforderung:** Preis runter 

Mail-Auszug
nach eingehender Prüfung könnten wir uns für 500 Flugbeutel einseitig bedruckt begeistern. Ein anderer Anbieter bietet uns diese bei gleicher Menge / Bearbeitung für € 700,- total (= Stückpreis € 1.40 inkl. Druck) an. Wir haben jedoch mit Ihrem Hause gute Erfahrungen gemacht und würden den Auftrag gern regional vergeben.

**Comment by aobermeier** [comment]
Guten Tag Herr Obermeier,

vielen Dank für Ihre positive Rückmeldung.

Bitte beachten Sie, dass der von uns angebotene Flugbeutel den EU Handgepäckbestimmungen für den Flugverkehr entspricht.

Es gibt günstigere Modelle, welche diese Zertifizierung nicht haben. 


Ich habe wegen des Preises Rücksprache mit meinem Vorgesetzten gehalten. 

**Sollten Sie sich für die Tassen ebenfalls begeistern, kann ich Ihnen aufgrund des höheren Auftragsvolumen mehr entgegen kommen.** 

**Bei Einzelbestellung der Flugbeutel kann ich Ihnen etwas entgegenkommen und einen Preis von 1,72 €/Stk anbieten.** 

Gerne kann ich Ihnen ein Muster zum Preis von 1,72 €/Stk + 5,50 € Versandkosten zukommen lassen. 


Bitte bestätigen Sie mir kurz die Musterbestellung.

**Comment by aobermeier** [comment]
Rücksprache mt Hr. Nemeth bzgl. Angebot Rastal-Tasse http://www.werbemittel24.com/siena-porzellantasse-von-rastal.html

Da Zusendung des Flugbeutelmusters vom Porto zu teuer und nicht beim Anbieter direkt vor Ort, hier Abbildung:

![abbildung_flugbeutel](https://cloud.githubusercontent.com/assets/25026324/22290197/ceb70be4-e2ff-11e6-9a30-fa9307900f16.jpg)

**Comment by Geschaeftsfuehrer** [comment]
Bitte 500 Stück mit einseitiger AAS Augsburg Air Service Bedruckung (ohne Flugzeug), Preis 1,72€ ohne Tassen zur Zeit.  In der Flugbeutel Qualität.

FK

**Comment by aobermeier** [comment]
Wird gemacht - **letzte Fragen:** 

Logo eher im oberen Drittel des Flugbeutels oder in der Mitte? 
Sollen wir das "Augsburg Air Service" (unter dem roten Part) in Weiß drucken lassen statt grau, damit man's besser sieht?

**Comment by Geschaeftsfuehrer** [comment]
Das Logo mittig ! Und so groß wie möglich, da Hintergrund Transparent und zum Wiedererkennungswert in grau ohne Flieger !!!

**Comment by aobermeier** [comment]
500 Stck, bestellt, 

Logo Rot = Sonderfarbe HKS 15N / Grau = Schwarzwert 55k (bei CYMK) oder Pantone 8C, Position: Höhe (und einigermaßen zentral mittig auf der Querachse) auf dem Flugbeutel positioniert, möglichst groß

**Comment by aobermeier** [comment]
**Unsere Antwort auf 1. Korrekturabzug:**

Druckgröße von 60 mm Breite noch zu klein, wir bevorzugen mind. 80 mm, bevorzugt 90 mm. 
Position wäre ok.

Wir wollten auch noch fragen, ob oben links unter dem Zipper die Team-d-GmbH-Adresse bitte weg kann. Wir möchten in diesem Fall ausschließlich für unser eigenes Unternehmen werben. 
Sollte dies nicht möglich sein, bitten wir darum, dass Team-d sich in der Bodenfalte verewigt.

**Comment by aobermeier** [comment]
2. Korrekturabzug mit Logo 80 mm liegt bei Fr. Dewald, bitte kurz draufschauen und wenn ok ggf. abzeichnen, damit produktion starten kann.

**Antwort bzgl. Adressanbringung Hersteller:** Der Hersteller ist nach dem Produktsicherheitsgesetz dazu verpflichtet, seine Adresse auf dem Artikel anzubringen. Leider ist diese an der (etwas unglücklichen) Position bereits standardmäßig aufgedruckt. Ein Aufkleber kommt leider auch nicht in Frage, da man die Adresse weiterhin von der anderen Seite sehen würde. Auf der Bodenfalte besteht die Gefahr, dass sich ein Druck lösen könnte, da diese leicht verknittert. **Das können wir leider nicht umgehen.**

**Comment by aobermeier** [comment]
Zwischenstatus: Anbieter versucht Herstelleraufdruck auf Rückseite zu bekommen. **Antwort dazu erfolgt morgen.**

Bei Bestellung diese Woche: Liefertermin Anfang März

**Comment by Geschaeftsfuehrer** [comment]
Ok, muss dann auch Mitte März spätestens da sein, da es weiter zu Embraer geschickt werden muss.

**Comment by aobermeier** [comment]
**Antwort hersteller:** die Team-D Adresse wird im Inneren des Beutels **eingenäht** und ist somit bei Befüllung sowieso abgedeckt.  Hier gab es einen kleinen Kommunikationsfehler zwischen dem Lieferanten und mir.

Zudem ist das auf dem Korrekturabzug etwas unglücklich dargestellt.

**Comment by aobermeier** [comment]
Bestellung ist raus.

**Comment by aobermeier** [comment]
[Auftragsbestätigung 1269159.pdf](https://github.com/aobermeier/Work/files/747807/Auftragsbestatigung.1269159.pdf)

**Comment by aobermeier** [comment]
Angekommen, aber nicht zufriedenstellend. Druck nicht gleichmäßig, teilweise schief verschweißt, teilweise Schmierer/fahrer auf Oberfläche. Unklar, ob wir 100 raussortieren oder gleich alles zurücksenden, ggf. ansehen.

Muster liegen bei Fr. Dewald.

**Comment by Geschaeftsfuehrer** [comment]
Wie Frau Dewald gestern schon sagte. Alle zurück zuschicken.


Mit freundlichen Grüßen
Florian Kohlmann
Augsburg Air Service GmbH, Augsburg

**Comment by aobermeier** [comment]
Ware bemängelt, Interwerbung sieht es genauso.
Ware im lager zur Abholung für Lieferant (Wunsch interwerbung(

Interwerbung möchte gern div. Lösungsvorschläge machen, das warte ich noch ab. Wir können aber jederzeit vom Auftrag ganz zurücktreten.

**Comment by aobermeier** [comment]
Heute Mahnung eingetroffen. Mahnung gestoppt, Beweismails Mängelrüge gesandt. 

Der zuständige Mitarbeiter Hr. Nemeth ist krank. Telefonat Hr. Räther hat ergeben, dass **Ware** (k.A. welcher Zustand / Neuproduktion?) **wieder auf dem Weg zu uns ist**. Schriftl. Beweis erbracht, dass Zieltermin überschritten und auch so kommuniziert worden ist.

Nun Recherche Hr. Räther zur Lösung. Wenn Ware eintrifft, erstmal annehmen und abwarten. Ware kann gesichtet werden, auch wenn wir keinen Bedarf mehr haben. Info an Lager weitergegeben (Hr. Hauser)

**Comment by aobermeier** [comment]
schon lang erledigt
