### ISSUE TITLE
Social Media News

### ISSUE THREAD

**Issue by Geschaeftsfuehrer** [aobermeier/Work#13]
Fotos vom Umbau , liegen unter F:\Allgemein\Bilder allgemein\_2017 Büroräume\Auswahl

**Comment by aobermeier** [comment]
Alles klar, 

Herr. Erz. liefert mir fehlendes Bild von deinem Raum noch morgen - **Facebook-Schaltung dann morgen, wenn alles beisammen**

**Comment by Geschaeftsfuehrer** [comment]
Welches fehlende Bild ?

**Comment by aobermeier** [comment]
Guten Morgen Andreas,

das Büro der technischen Leitung fehlt noch. Wollte es heute Früh machen, standen aber im Stau und ich versuche es morgen Früh zu erledigen.

Mit freundlichen Grüßen
Thomas Erz

**Comment by aobermeier** [comment]
Post am 01.02 erledigt
