### ISSUE TITLE
Vorschlag Werbegeschenke Schlüsselanhänger Carbon

### ISSUE THREAD

**Issue by aobermeier** [aobermeier/Work#29]
Anbei https://tinyurl.com/z5wpwfo

kann soweit ich gesehen habe, HINTEN graviert werden.
Nachdem Adler nicht der günstigste Anbieter für Mindermengen ist, vlt. Recherche bei anderen Anbietern od. Gemeinschaftsproduktion mit Atlas. 

Bei gefallen einfach an Fr. mamic weiterleiten + Issue closen, ansonsten als Reminder stehenlassen.

**Comment by Geschaeftsfuehrer** [comment]
Will heut keiner mehr. Macht den Schlüsselbund nur schwer und nutz die Schlüssel ab. Zusätzlich hat es keine Funktion, Lampe, etc. ............
