### ISSUE TITLE
Website Home Trailer , Start with Embraer - 30.01

### ISSUE THREAD

**Issue by Geschaeftsfuehrer** [aobermeier/Work#9]
Ab.30.01.2017 bis mindestens 1.04.17.

**Comment by aobermeier** [comment]
30.01 ist bereits kommenden Montag und wir haben noch nicht einmal eine Pressemeldung. Könnte bei den Kunden etwas für Verwirrung sorgen...

Vorschlag wäre: ab 15.03, 

Wenn keine Antwort bis Arbeitsschluß heute erfolgt, schalte ich automatisch am Montag

**Comment by aobermeier** [comment]
Vorschau:
![preview_bild_050_embraer_sc](https://cloud.githubusercontent.com/assets/25026324/22422348/22f0fdec-e6ec-11e6-8b49-cb37215badfd.jpg)

Sequenz: 
[sequ_050.pdf](https://github.com/aobermeier/Work/files/738821/sequ_050.pdf)

**Wenn so ok, kurzes "go" bitte.** Nicht dass ich als Botschaft das mit dem Sponsoring hätt schalten sollen.

**Comment by Geschaeftsfuehrer** [comment]
Sieht sehr gut aus, bitte umsetzen.

**Comment by aobermeier** [comment]
erledigt, wird als Bild 1 eingeblendet http://www.aas-augsburg.de/index.php?id=3
